'use client'
import { useDispatch } from "react-redux"
import { ImageEntity } from "../../domain/entities/Image.entity"
import { useState } from "react"
import { lookImageData } from "../../image-slice/image.slice"
import { openModalWrapper } from "@/modules/shared/common/common-slice/modals-slice.store"

export interface ImageCardProps{
    image:ImageEntity
}
export default function ImageCard({image}:ImageCardProps) {
    const [loaded, setLoaded] = useState(false)
    const [id,setId]=useState('')
    const dispatch =useDispatch()
    const onClickOpenImageDataModal =(image:ImageEntity)=>{
        document.body.style.overflow = "hidden"
        dispatch(lookImageData(image))
        dispatch(openModalWrapper({title:'About your image'}))
    }
  return (
    <div className=" gap-4 rounded-lg relative   flex flex-col " >
            {!loaded && 
                (<div className="absolute inset-0 bg-gray-200 animate-pulse rounded-lg" />)
            }
            <div 
                className="flex h-full overflow-hidden relative"
            >   
                <div 
                    className={` cursor-pointer flex items-end rounded-lg
                        ${image.id === id ? "bg-black/30":""} absolute bottom-0 left-0 right-0 top-0`} 
                    onClick={()=>onClickOpenImageDataModal(image)}
                    onMouseLeave={()=>setId('')} 
                    onMouseEnter={() => setId(image.id)} 
                >
                    <div className={`flex items-center justify-end gap-2 w-full rounded-lg p-2 ${image.id===id ? "block":"hidden"}`}>
                        <p className="text-md text-pink-600 font-semibold">Prompt</p>
                        <p className="text-sm text-white truncate whitespace-nowrap grow pr-5">{image.prompt}</p>
                    </div>
                </div>
                <img
                    src={image.imageUrl}
                    alt="ai-image generated by mokka application"
                    onLoad={() => setLoaded(true)}
                    className={`h-full w-full object-cover rounded-md transition-opacity duration-500 ${
                        loaded ? "opacity-100" : "opacity-0"
                    }`}
                />
            </div>
    </div> 
  )
}
