"use client";

import { useIdSession } from "@/modules/shared/auth/view/custom-hooks/useIdSession";
import { RootState } from "@/store/boundStore";
import { useDispatch, useSelector } from "react-redux";
import { IoShareSocialOutline } from "react-icons/io5";
import { GoTag } from "react-icons/go";
import { ApiErrorPlatform } from "@/modules/shared/common/errors/api-errors.error";
import {
  SelectorModalbasedError,
  TypeErrorAlert,
} from "@/modules/shared/common/infrastructure/error-mappers/selector-modal-based-error.mapper";
import { setConfigAlertModal } from "@/modules/shared/common/common-slice/modals-slice.store";
import { sileo } from "sileo";
import { IoCopyOutline } from "react-icons/io5";
import { BsArrowsAngleExpand } from "react-icons/bs";
import { FaPaintbrush } from "react-icons/fa6";
import { useState } from "react";
import DownloadImageButton from "./DownloadImageButton";


export default function ImageDataModal() {
    const [isPending, setIsPending] = useState(false)
  const currentImageData = useSelector(
    (state: RootState) => state.image.currentImageData,
  );
  const dispatch = useDispatch();
  const { id } = useIdSession();
  const shareCurrentImage = () => {
    if(!id) return
    try {

    } catch (error) {
      if (error instanceof ApiErrorPlatform) {
        const config = SelectorModalbasedError.selectModal(error);
        if (config.typeAlert === TypeErrorAlert.ALERT_MODAL) {
          dispatch(
            setConfigAlertModal({
              title: config.title,
              message: config.message,
              type: "error",
            }),
          );
        } else {
          sileo.error({
            title: config.title,
            description: config.message,
          });
        }
      } else {
        sileo.error({
          title: "Unexpected Error",
          description: "An unknown error occurred. Please try again later.",
        });
      }
    }finally{
        setIsPending(false)
    }
  };
  return (
    <>
      <div className="flex gap-4">
        <div className="w-1/2 h-full flex flex-col gap-2">
          <div className="grow rounded-lg overflow-hidden">
            <img
              src={currentImageData?.imageUrl}
              className="object-content rounded-lg"
              alt={`image generated by mokka: ${currentImageData?.prompt}`}
            />
          </div>
        </div>

        <div className="w-1/2 flex flex-col gap-4">
          <div className="space-y-2">
            <div className="flex items-center">
              <label
                htmlFor="promptInfo"
                className="w-full grow flex items-center gap-2 text-lg font-semibold"
              >
                <GoTag size={18} />
                Prompt
              </label>
              <button
                className="cursor-pointer hover:text-gray-400 transition-colors"
                type="button"
              >
                <IoCopyOutline size={18} />
              </button>
            </div>
            <p className="text-md py-2 px-4 rounded-lg bg-slate-50">
              {currentImageData?.prompt}
            </p>
          </div>

          <div className="space-y-2">
            <label
              htmlFor="technicalInfo"
              className="w-full flex items-center gap-2 text-lg font-semibold"
            >
              <BsArrowsAngleExpand size={18} />
              Technical specifications
            </label>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-sky-100 p-2 rounded-lg ">
                <label
                  htmlFor="resolution"
                  className="text-md text-sky-600 font-semibold"
                >
                  Resolution
                </label>
                <p className="font-semibold text-lg text-sky-800">
                  {currentImageData?.width}x{currentImageData?.height}
                </p>
              </div>
              <div className="bg-pink-100 p-2 rounded-lg">
                <label
                  htmlFor="aspectRatio"
                  className="text-pink-600 font-semibold text-md"
                >
                  Aspect ratio
                </label>
                <p className="text-lg text-pink-800 font-semibold">
                  {currentImageData?.aspectRatio}
                </p>
              </div>
              <div className="bg-lime-100 p-2 rounded-lg">
                <label
                  htmlFor="size"
                  className="text-lime-600 font-semibold text-md"
                >
                  Size
                </label>
                <p className="text-lg text-lime-800 font-semibold">
                  {currentImageData?.size}
                </p>
              </div>
              <div className="bg-purple-100 p-2 rounded-lg">
                <label
                  htmlFor="date"
                  className="text-purple-600 font-semibold text-md"
                >
                  Creation date
                </label>
                <p className="text-lg text-purple-800 font-semibold">
                  {currentImageData?.createDate}
                </p>
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <label
              htmlFor="styleInfo"
              className="w-full flex items-center gap-2 text-lg font-semibold"
            >
              <FaPaintbrush size={18} />
              Image style
            </label>
            <div className="grid grid-cols-2 gap-4">
              <div className="p-2 rounded-lg bg-slate-100">
                <label
                  htmlFor="style"
                  className="text-black font-semibold text-md"
                >
                  Style
                </label>
                <p className="text-lg font-semibold text-black">
                  {currentImageData?.style
                    ? currentImageData?.style
                    : "No specific"}
                </p>
              </div>
              <div className="p-2 rounded-lg bg-slate-100">
                <label
                  htmlFor="substyle"
                  className="text-black font-semibold text-md"
                >
                  Substyle
                </label>
                <p className="text-lg font-semibold text-black">
                  {currentImageData?.subStyle
                    ? `${currentImageData?.subStyle}`
                    : "No specific"}
                </p>
              </div>
            </div>
          </div>

          <div className="flex items-end gap-4 grow">
            {currentImageData && (
              <DownloadImageButton imageUrl={currentImageData?.imageUrl} />
            )}
            <button
              className="w-1/2 py-3 flex items-center gap-2 cursor-pointer font-medium justify-center bg-pink-700 text-white hover:text-black rounded-2xl transition-colors"
              onClick={shareCurrentImage}
              disabled={isPending}
            >
              <IoShareSocialOutline size={20} />
              {isPending ? "Sharing..." : "Share"}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
